builds:
  - binary: faas-nomad
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm
    goarm:
      - 6
      - 7
    env:
      - CGO_ENABLED=0
      - arm64

release:
	name_template: "{{.ProjectName}}-v{{.Version}}"

dockers:
  - 
    binary: faas-nomad
    image: quay.io/nicholasjackson/faas-nomad
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    latest: true
    tag_template: "{{ .Tag }}"
  - 
    binary: faas-nomad
    image: quay.io/nicholasjackson/faas-nomad
    goos: linux
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile_arm7
    tag_template: "arm7-{{ .Tag }}"
