builds:
  - binary: faas-nomad
    ldflags: -s -w -X main.version=dev
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm
    goarm:
      - 6
      - 7
    env:
      - CGO_ENABLED=0

dockers:
  - 
    binary: faas-nomad
    image: quay.io/nicholasjackson/faas-nomad
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    tag_templates: 
      - "latest"
      - "{{ .Tag }}"
      - "{{.Version}}"
  - 
    binary: faas-nomad
    image: quay.io/nicholasjackson/faas-nomad
    goos: linux
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile_arm7
    tag_templates: 
      - "arm7-{{ .Tag }}"
      - "arm7-{{.Version}}"
