FROM arm32v6/alpine

RUN adduser -h /home/faasnomad -D faasnomad faasnomad

COPY ./dist/linuxarm7/faas-nomad /home/faasnomad/
RUN chmod +x /home/faasnomad/faas-nomad

USER faasnomad

ENTRYPOINT ["/home/faasnomad/faas-nomad"]
